name: run-tests

on:
  push:
    branches: [master,workflow]
  pull_request:

env:
  AFRICASTALKING_USERNAME: ${{ secrets.AFRICASTALKING_USERNAME }}
  AFRICASTALKING_API_KEY: ${{ secrets.AFRICASTALKING_API_KEY }}
#  AFRICASTALKING_ALPHANUMERIC: ${{ secrets.AFRICASTALKING_ALPHANUMERIC }}
#  AFRICASTALKING_BACKUP_SENDERID: ${{ secrets.AFRICASTALKING_BACKUP_SENDERID }}
#  AFRICASTALKING_PAYMENT_PRODUCT: ${{ secrets.AFRICASTALKING_PAYMENT_PRODUCT }}
#  AFRICASTALKING_PREMIUM_SHORTCODE: ${{ secrets.AFRICASTALKING_PREMIUM_SHORTCODE }}
#  AFRICASTALKING_VOICE_PHONE_NUMBER: ${{ secrets.AFRICASTALKING_VOICE_PHONE_NUMBER }}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [7.3, 7.4, 8.0, 8.1, 8.2]
        stability: [prefer-lowest, prefer-stable]

    name: P${{ matrix.php }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: pcov

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Create test Fixture.php
        run: cp tests/Fixtures.php.tpl tests/Fixtures.php

      - name: Install dependencies
        run: |
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction
          composer require --dev --with-all-dependencies vlucas/phpdotenv
          php test.php

      - name: Execute tests
        run: ./vendor/bin/phpunit